// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"Go-Zero/user-rpc/internal/logic"
	"Go-Zero/user-rpc/internal/svc"
	"Go-Zero/user-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
